### ISSUE TITLE
incorrect PCL Profile for Analytics

### ISSUE THREAD

**Issue by ftb59** [ctacke/opennetcf#2]
Hi,

I'm trying to use your library for google analytics however I'm facing an issue due to my profile choice, do you know which one should I use for Xamarin Forms?

> Adding com.opennetcf.analytics.google.pcl...
> Attempting to resolve dependency 'Xamarin.Forms (≥ 2.0.0)'.
> Adding 'com.opennetcf.analytics.google.pcl 1.0.16202.0' to XXXXXX.
> Could not install package 'com.opennetcf.analytics.google.pcl 1.0.16202.0'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+Xamarin.TVOS10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
> 
> 

Thanks a lot,
Regards,

**Comment by ctacke** [comment]
I developed and tested using Xamarin Forms Protable.  Which version of Xamarin Forms are you targeting, and which project type is this failing on (Xamarin.Forms Shared or portable, or one of the platform-specific projects)?

**Comment by ctacke** [comment]
I've also updated the library to vastly improve the user-agent reporting, which I just released.  See if maybe the newer version (16230.2) fixes your issue.

**Comment by ftb59** [comment]
It fixed it, thank you so much @ctacke

**Comment by dakamojo** [comment]
I also have this issue with the latest version (1.0.16230.2).  I'm adding it to the PCL portion of my Xamarin.Forms project.  Xamarin.Forms is version 2.3.1.114.  Here is the relevant portion of the log.

Successfully installed 'com.opennetcf.analytics.google.pcl 1.0.16230.2'.
Adding 'com.opennetcf.analytics.google.pcl 1.0.16230.2' to WootDashboardXF.
Could not install package 'com.opennetcf.analytics.google.pcl 1.0.16230.2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ctacke** [comment]
Hmm, the nuspec lists this:

portable-net45+netcore45+wpa81+wp8+monoandroid+monotouch+xamarinios10+xamarinmac

I would think the portable-net45 would cover you.  Do you have a simple project or repro steps that I can use to duplicate this?  I created a simple project and it worked, but i want to make sure I get you covered.

**Comment by dakamojo** [comment]
I created a brand new Xamarin.Forms project.  The default profile is still the same, PCL 4.5 Profile 78.  I have Xamarin Studio 6.0.2 build 73.  The project has Xamarin.Forms 2.0.1.6495 initially (update available).  Before updating Xamarin.Forms I tried to add your nuget.  Here is the complete log.

Adding com.opennetcf.analytics.google.pcl...
Attempting to resolve dependency 'Xamarin.Forms (≥ 2.0.0)'.
Installing 'com.opennetcf.analytics.google.pcl 1.0.16230.2'.
Added file 'OpenNETCF.Google.Analytics.Android.dll' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/monoandroid+monotouch'.
Added file 'OpenNETCF.Google.Analytics.Android.pdb' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/monoandroid+monotouch'.
Added file 'OpenNETCF.Google.Analytics.dll' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/monoandroid+monotouch'.
Added file 'OpenNETCF.Google.Analytics.pdb' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/monoandroid+monotouch'.
Added file 'OpenNETCF.Google.Analytics.dll' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/Xamarin.iOS10'.
Added file 'OpenNETCF.Google.Analytics.iOS.dll' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/Xamarin.iOS10'.
Added file 'OpenNETCF.Google.Analytics.iOS.pdb' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/Xamarin.iOS10'.
Added file 'OpenNETCF.Google.Analytics.pdb' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/lib/Xamarin.iOS10'.
Added file 'OpenNETCF.Google.Analytics.dll' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/portable-net45+netcore45+wpa81+wp8+monoandroid+monotouch+xamarinios10+xamarinmac'.
Added file 'OpenNETCF.Google.Analytics.pdb' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2/portable-net45+netcore45+wpa81+wp8+monoandroid+monotouch+xamarinios10+xamarinmac'.
Added file 'com.opennetcf.analytics.google.pcl.1.0.16230.2.nupkg' to folder 'com.opennetcf.analytics.google.pcl.1.0.16230.2'.
Successfully installed 'com.opennetcf.analytics.google.pcl 1.0.16230.2'.
Adding 'com.opennetcf.analytics.google.pcl 1.0.16230.2' to Sample.
Could not install package 'com.opennetcf.analytics.google.pcl 1.0.16230.2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I updated Xamarin.Forms to 2.3.114 and tried adding your nuget again.  Here is the log.

Adding com.opennetcf.analytics.google.pcl...
Attempting to resolve dependency 'Xamarin.Forms (≥ 2.0.0)'.
Adding 'com.opennetcf.analytics.google.pcl 1.0.16230.2' to Sample.
Could not install package 'com.opennetcf.analytics.google.pcl 1.0.16230.2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ctacke** [comment]
Wondering if it's the "+win".  I'll do some testing and packaging.

**Comment by ctacke** [comment]
Give the new .3 release a try

**Comment by dakamojo** [comment]
That worked.  The package installed without error.  Thanks.
